In [ ]:
import statsmodels.api as sm
import numpy as np

# Generate some example data
np.random.seed(0)
X = np.random.normal(0, 1, (100, 1))
y = 2 * X[:, 0] + np.random.normal(0, 1, 100)

# Fit the linear regression model
X = sm.add_constant(X)  # Add constant column for intercept
model = sm.OLS(y, X).fit()

mean: The mean or average predicted value.
mean_se: The standard error of the mean prediction.
mean_ci_lower: The lower bound of the confidence interval for the mean prediction.
mean_ci_upper: The upper bound of the confidence interval for the mean prediction.
obs_ci_lower: The lower bound of the prediction interval.
obs_ci_upper: The upper bound of the prediction interval.

In [3]:
pred = model.get_prediction(sm.add_constant(X)).summary_frame(alpha=0.1)
pred

,mean,mean_se,mean_ci_lower,mean_ci_upper,obs_ci_lower,obs_ci_upper
0,3.805592,0.204037,3.466778,4.144405,2.047933,5.563250
1,0.921365,0.109625,0.739327,1.103402,-0.812909,2.655639
2,2.144889,0.140552,1.911495,2.378282,0.404475,3.885303
3,4.813966,0.247599,4.402815,5.225118,3.040942,6.586991
4,4.024475,0.213287,3.670301,4.378649,2.263791,5.785159
...,...,...,...,...,...,...
95,1.569342,0.123408,1.364416,1.774268,-0.167484,3.306168
96,0.097357,0.103987,-0.075318,0.270033,-1.635959,1.830674
97,3.851731,0.205975,3.509698,4.193763,2.093449,5.610013
98,0.343534,0.104093,0.170683,0.516385,-1.389800,2.076868
99,0.925239,0.109685,0.743101,1.107377,-0.809045,2.659524